import React, { useEffect, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { ArrowUpRight, ArrowRight, Menu, X, MapPin } from 'lucide-react'
import { company, services } from './company'
import './style.css'
import './theme.css'

const nav = ['Services', 'About', 'Location', 'Contact']
const flakes = Array.from({ length: 48 }, (_, i) => ({ left: `${(i * 37) % 101}%`, delay: `${-((i * 19) % 80) / 10}s`, duration: `${5 + (i % 6) * .65}s`, size: `${3 + (i % 5) * 2}px` }))
function SnowText({ text }: { text: string }) {
 return <span className="snow-text" aria-label={text}>{[...text].map((letter, i)=><span aria-hidden="true" className="snow-char" style={{'--delay': `${i * .028}s`, '--drift': `${((i % 7) - 3) * 11}px`} as React.CSSProperties} key={`${letter}-${i}`}>{letter === ' ' ? '\u00a0' : letter}</span>)}</span>
}
function App() {
 const [menu, setMenu] = useState(false); const [scrolled, setScrolled] = useState(false)
 useEffect(() => { const f=()=>setScrolled(scrollY>30); addEventListener('scroll', f,{passive:true}); document.documentElement.classList.add('snow-ready','text-snow-ready'); const snowObserver=new IntersectionObserver(entries=>entries.forEach(entry=>entry.isIntersecting&&entry.target.classList.add('snow-settled')),{threshold:.3}); const textObserver=new IntersectionObserver(entries=>entries.forEach(entry=>entry.isIntersecting&&entry.target.classList.add('text-settled')),{threshold:.16}); document.querySelectorAll('.snow-text').forEach(el=>snowObserver.observe(el)); document.querySelectorAll('header .brand, header button, main p, main h1, main h2, main h3, main button, main address, main small, main li, main .owner-photo, main .bolero-stage, footer .brand, footer span, footer button').forEach(el=>{el.classList.add('text-snow');textObserver.observe(el)}); return()=>{removeEventListener('scroll',f);snowObserver.disconnect();textObserver.disconnect()}}, [])
 const jump=(id:string)=>{ setMenu(false); document.getElementById(id)?.scrollIntoView({behavior:'smooth'}) }
 return <><div className="snowfall" aria-hidden="true">{flakes.map((flake,i)=><i key={i} style={{left:flake.left,'--fall-delay':flake.delay,'--fall-duration':flake.duration,'--flake-size':flake.size} as React.CSSProperties}/>)}</div><div className="progress" />
 <header className={scrolled ? 'nav nav--solid':'nav'}><a className="brand" href="#top" aria-label="Coldigo Logistics home"><i/>COLDIGO <span>LOGISTICS</span></a><nav>{nav.map(x=><button key={x} onClick={()=>jump(x.toLowerCase())}>{x}</button>)}</nav><button className="menu" aria-label="Open menu" onClick={()=>setMenu(true)}><Menu/></button></header>
 <aside className={menu?'overlay show':'overlay'}><button aria-label="Close menu" onClick={()=>setMenu(false)}><X/></button>{nav.map(x=><a href={'#'+x.toLowerCase()} onClick={()=>setMenu(false)}>{x}</a>)}<a href="#contact" onClick={()=>setMenu(false)}>Get in touch <ArrowRight/></a></aside>
 <main id="top"><section className="hero"><div className="hero-grid"/><div className="orb orb-a"/><div className="orb orb-b"/><div className="hero-route"><svg viewBox="0 0 900 500" aria-hidden="true"><path d="M-20,440 C150,380 150,160 350,230 S650,400 930,60"/><circle cx="350" cy="230" r="8"/></svg></div><div className="hero-delivery" aria-hidden="true"><div className="hero-city city-origin"><span>DESTINATION</span></div><div className="hero-city city-destination"><span>HYDERABAD</span></div><div className="hero-road"><i/><i/><i/><i/></div><div className="hero-pickup"><div className="hero-cargo">❄</div><div className="hero-cab"><b/></div><i className="hero-wheel wheel-left"/><i className="hero-wheel wheel-right"/></div></div><div className="hero-copy"><p className="eyebrow"><MapPin size={13}/> HYDERABAD · TELANGANA</p><h1><span className="hero-line">Cold Transport,</span><br/><em><span className="hero-word hero-word--on">On time,</span> <span className="hero-word hero-word--every">every time.</span></em></h1><p className="lead">Reliable logistics and transportation solutions built around precision, movement and dependable execution.</p><button className="button" onClick={()=>jump('contact')}>Start a conversation <ArrowUpRight/></button></div><div className="hero-meta"><span>SCROLL TO EXPLORE</span><b/><span>01 — 06</span></div></section>
 <section id="about" className="intro section"><div className="approach-visual" aria-hidden="true"><i className="approach-orbit orbit-one"/><i className="approach-orbit orbit-two"/><b className="approach-point point-a"/><b className="approach-point point-b"/><b className="approach-point point-c"/></div><p className="section-no">01</p><div className="intro-story"><p className="eyebrow dark">THE COLDIGO APPROACH</p><h2><SnowText text="Logistics is"/><br/><SnowText text="more than"/><br className="intro-mobile-break"/> <SnowText text="moving"/><br/><em><SnowText text="from A to B."/></em></h2><p className="intro-copy">It is the coordination behind every handoff, the clarity behind every decision and the care taken to keep things moving. Coldigo Logistics is positioned around dependable movement and thoughtful execution.</p><div className="intro-signal"><i/><span>COORDINATION / CLARITY / CARE</span></div></div></section>
 <section className="movement section"><div className="movement-head"><h2><SnowText text="Designed for the"/><br/><em><SnowText text="way forward."/></em></h2></div><div className="route-card"><div className="route-top"><span>ROUTE ACTIVE</span><span>HYDERABAD</span><span>IN TRANSIT</span></div><svg viewBox="0 0 1000 260" preserveAspectRatio="none"><path d="M0 180 C210 50 330 280 520 120 S790 100 1000 40"/><circle cx="520" cy="120" r="9"/><circle cx="850" cy="74" r="6"/></svg><div className="route-bottom"><b>ORIGIN</b><span>→</span><b>DESTINATION</b></div></div></section>
<section className="india-network section" aria-label="India delivery map"><div className="network-copy"><h2><SnowText text="Routes in"/><br/><em><SnowText text="motion."/></em></h2><p>Live vehicle locations across India give clients a clear view of our active fleet, while Coldigo keeps every delivery moving with temperature-conscious handling, clear coordination and a promise to arrive on time.</p></div><div className="india-stage"><img className="route-map-image" src="/india-map.avif" alt="Map of India showing live Coldigo vehicle locations"/>{[2,7,8,9,10].map(i=><i aria-hidden="true" className={`india-vehicle point-${i}`} key={i}>▸</i>)}</div></section>
 <section className="bolero section"><div className="bolero-copy"><h2><SnowText text="Cool cargo."/><br/><em><SnowText text="Clear movement."/></em></h2><p>This visual represents temperature-conscious transport: a protected load, a defined route and responsive coordination from start to finish.</p><p className="bolero-caption">A practical way to think about cold transport, where every movement is planned with care.</p></div><div className="bolero-stage" aria-label="Animated refrigerated pickup illustration"><div className="snow-mountain m-one"/><div className="snow-mountain m-two"/><div className="bolero-road"><i/><i/><i/></div><div className="pickup"><div className="pickup-box"><span>❄</span></div><div className="pickup-cab"><i/></div><b className="wheel w-one"/><b className="wheel w-two"/></div></div></section>
 <section id="services" className="services section"><div className="services-title"><h2><SnowText text="What keeps"/><br/><em><SnowText text="moving."/></em></h2><p>Service categories are intentionally marked in code pending confirmation of Coldigo’s portfolio.</p></div><div className="service-list">{services.map(([n,t,d])=><article className="service" key={n}><span>{n}</span><div><h3>{t}</h3><p>{d}</p></div><ArrowUpRight/></article>)}</div></section>
 <section className="trust"><div><p className="eyebrow">LOCAL PRESENCE</p><h2>Hyderabad.<br/><em>In motion.</em></h2></div><div className="trust-facts"><div><strong>{company.rating}</strong><span>LOCAL LISTING RATING<br/><small>Based on {company.reviewCount} public reviews</small></span></div><div><strong>TS</strong><span>TELANGANA<br/><small>LOGISTICS SERVICE</small></span></div></div></section>
 <section id="location" className="location section"><div><p className="eyebrow dark">LOCATION</p><h2>Find us</h2><p className="hours">{company.hours}</p>{company.mapUrl && <a className="text-btn" href={company.mapUrl} target="_blank" rel="noreferrer">View location <ArrowUpRight/></a>}</div><div className="map-art"><iframe title="Coldigo Logistics location" src={company.mapEmbedUrl} loading="eager" referrerPolicy="no-referrer-when-downgrade"/><span className="map-lock" aria-hidden="true"/>{company.mapUrl && <a className="map-fallback" href={company.mapUrl} target="_blank" rel="noreferrer">Open location map <ArrowUpRight size={14}/></a>}</div></section>
 <section className="owner section" aria-labelledby="owner-title"><div className="owner-photo"><img src="/sohail-khan.jpeg" alt="Portrait supplied for Sohail Khan's owner profile"/></div><div className="owner-copy"><p className="eyebrow dark">THE PERSON BEHIND THE MOVEMENT</p><h2 id="owner-title"><SnowText text="A vision"/><br/><em><SnowText text="in motion."/></em></h2><p className="owner-lead">Sohail Khan was born in Jammu &amp; Kashmir and raised in Hyderabad, bringing a data-aware, digital-first perspective to the next chapter of transport in India.</p><p>Specialised in Business Analytics, he later spent three years as a Digital Marketing expert. Today, he is channelling that experience into practical, innovative ideas for a more modern, connected and customer-focused transport industry.</p><ul><li>Business analytics perspective</li><li>Three years in digital marketing</li><li>A vision for transport innovation in India</li></ul></div></section>
 <section id="contact" className="contact"><p className="eyebrow">START A CONVERSATION</p><h2>Let’s move<br/><em>something forward.</em></h2><p>Have a transportation or logistics requirement? Start a conversation with Coldigo Logistics.</p><form onSubmit={e=>{e.preventDefault(); alert('Thank you. This enquiry form is ready to connect to your preferred service.')}}><input required placeholder="Name" aria-label="Name"/><input placeholder="Company" aria-label="Company"/><input required type="tel" placeholder="Phone" aria-label="Phone"/><input required type="email" placeholder="Email" aria-label="Email"/><textarea required placeholder="Requirement" aria-label="Requirement"/><button className="button">Submit enquiry <ArrowUpRight/></button></form></section>
 </main><footer><a className="brand" href="#top"><i/>COLDIGO <span>LOGISTICS</span></a><span>Hyderabad, Telangana</span><span>© {new Date().getFullYear()} Coldigo Logistics</span><button onClick={()=>jump('top')}>BACK TO TOP ↑</button></footer></> }
createRoot(document.getElementById('root')!).render(<App />)
